spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ENC(mXJrvAI3C5biImJLp54fi0jzdn+TVz2uIkOoPq7fcVP6Q6k52Y0CM6sN9CgMWMil)
            client-secret: ENC(iqbugq2ytRRJG86/kpghqx1k5e1/XhTZdGWVUFOsN7sUpEBAe+R7cqgfIxt0pbV1)
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - phone_number
              - name
              - account_email
            client-authentication-method: client_secret_post
            client-name: Kakao
          naver:
            client-id: ENC(/ZYibxNIGC6UgyCbvW3XHStNgq8Xuj96QSQU9xkgVZk=)
            client-secret: ENC(1w37YK5NIqabLLZ1kZdR+8L6Ly1kCtXu)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, mobile
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

