name: backend CI Config

on:
  push:
    paths: '/'
  pull_request:
    branches:
      - develop
      - main
    paths: '/'

defaults:
  run:
    working-directory: /

permissions:
  pull-requests: write
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give permission for Gradle
        run: chmod +x gradlew

      - name: Run gradle build
        run: ./gradlew build
